<?php
return [
    "Business Development - Mobile Apps",
    "Creative Content Writers",
    "Creative Graphic Designer",
    "iOS App Developer",
    "Sr. Software Engineer",
    "Storyboard Artist",
    "Editor & Proofreader",
    "UI/UX Designer-Mobile Apps",
    "Unity 2D/3D Mobile App. Game Developer",
    "Technical Support Executive",
    "Business Analyst",
    "Solution Architect",
    "Project Manager",
    "Digital - Brand Manager",
    "Social Media Executive",
    "Accountant",
    "Sales",
    "Customer Support",
    "SEO",
    "PPC",
    "Supply Chain/Logistics",
    "Business Development Executive",
    "Marketing",
    "Quality Assurance",
    "IT",
    "HR",
    "Web Designer",
    "BPO",
    "Account Manager - Mobile Applications",
    "React Native Developer",
    "Full Stack Developer",
    "Quality Assurance - Mobile Applications",
    "Chef",
    "Chinese Sales Consultant",
    "2D Video Animator",
    "Senior PHP Developer",
    "Android Developer",
    "Web Developer",
    "Frontend UI/UX Developer",
    "Senior Web Developer"
];
