<?php
return [
    "Virus related",
    "Email Issue",
    "Fonts Installation",
    "Other Software Installation",
    "Spark Issue",
    "Adobe Softwares Installation",
    "Soft-phone issue",
    "Windows Expire",
    "MS Office Expire",
    "Data Recovery",
    "Other Issue",
    "System running slow",
    "Sound not working",
    "UPS issue",
    "Mouse not working",
    "Keyboard not working",
    "LED display issue",
    "RAM upgrade",
    "Additional Hard Disk Required",
    "Other Issue",
    "Cisco not working",
    "Distortion on Calls",
    "Call not connecting",
    "Call Recording",
    "Other Issue",
    "Internet working slow",
    "Wireless not connecting",
    "Other Issue",
    "Finger scanning not working",
    "Other Issue"
];
